# -*- coding: utf-8 -*-
"""Group5_MainProgram

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nMHgHvWjPzKDRGNEzX2xJyfpJDkG2jTc
"""

# Functions and Variables


'''Functions, Variables, and Packages'''

from datetime import datetime
from validate_email import validate_email
from tabulate import tabulate

validation_options_Agree = {'y','Y','Yes','yes'}
validation_options_Disagree = {'n','N','No','no'}

### This is where you would input your credentials, like your name, address, e-mail, and etc.
def input_credentials():
    print('Please input the following:')
    name = input('Full Name: ')
    address = input('Address: ')
    e_address = input_credentials_email()
    province = input_credentials_province()
    print()
    return name, address, e_address, province.upper()

### This is the part of the code where it checks if the inputted e-mail is valid or not.
def input_credentials_email():
    while True:
        e_address = input('Email Address: ')
        is_valid = validate_email(e_address)
        if is_valid:
            break
        else:
            print("Invalid email address. Please try again.\n")
            continue
    return e_address

### This is where it checks if the inputted province is within the list.
def input_credentials_province():
    while True:
        province = input("Province: ('Pampanga'/'Tarlac'/'Zambales'/'Bataan') - ")
        if province.upper() in ['PAMPANGA', 'TARLAC', 'ZAMBALES', 'BATAAN']:
            break
        else:
            print("Please input a valid province.\n")
            continue
    return province

### This section asks the user if it wants to change any specific part of their credentials.
def change_credentials(name, address, e_address, province):
    print("Which one do you want to change? \n\t>>> A - Name\n\t>>> B - Address\n\t>>> C - Email Address\n\t>>> D - Province")
    choice = input("> ")
    match choice:
        case 'a'|'A':
            name = input('Full Name: ')
        case 'b'|'B':
            address = input('Address: ')
        case 'c'|'C':
            e_address = input_credentials_email()
        case 'd'|'D':
            province = input_credentials_province()
        case _:
            print('Restarting process... Next time, please type within the list: [A|B|C|D]')
    print()
    return name, address, e_address, province.upper()


### This section opens up the possible pick-up location options based on the users province.
def pickUp_Province(province):
    while True:
        match province:
            case 'PAMPANGA':
                placel = "Angeles (Angeles Plaza)"
                place2 = "San Fernando (SM City Telabastagan)"
                place3 = "Porac (SandBox Pampanga)"
                break
            case 'TARLAC':
                placel = "Capas (Ves Food Resort & Villas)"
                place2 = "San Jose (San Jose Plaza)"
                place3 = "Bamban (Goshen Resort and Hotel)"
                break
            case 'ZAMBALES':
                placel = "Olongapo (SM City Olongapo Central)"
                place2 = "Subic (The Meeting Place)"
                place3 = "San Antonio (CASA San Miguel)"
                break
            case 'BATAAN':
                placel = "Mariveles (Mariveles People's Park)"
                place2 = "Morong (Pawikan Conservation Center)"
                place3 = "Balanga (Plaza Mayor de Ciudad de Balanga)"
                break

    print('\t>>> A -',placel,'\n\t>>> B -',place2,'\n\t>>> C -',place3,'\n')

    while True:
        locPickUp = input ("Location Chosen > ")
        match locPickUp:
            case 'a'|'A':
                PickUp_place = placel
                break
            case 'b'|'B':
                PickUp_place = place2
                break
            case 'c'|'C':
                PickUp_place = place3
                break
            case _:
                print("Input a valid response. Please type within the list: [A|B|C]\n")
                continue
    return PickUp_place

### This is the main menu of the program. It shows the various vehicles the user could rent.
def showcase_cars():
    data = [[1, "Toyota Vios MT", '₱3,285.00', '₱3,875.00'], [2, "Toyota Altis AT", '₱4,040.00', '₱4,650.00'],
            [3, "Toyota Camry", '₱4,830.00', '₱5,465.00'], [4, "Toyota Innova", '₱4,430.00', '₱4,705.00'],
            [5, "Toyota Grandia", '₱5,550.00', '₱6,200.00']]
    print(tabulate(data, headers = ["Unit", "Model", "Self-Drive (24hrs/d)", "Chauffeur Drive (10hrs/d)"]))

### This part asks the user what type of vehicle are they going to pick. It gives some additional info once the user pick one.
def choose_car(type_ofService):
    continue_Agree = True
    while continue_Agree:
        try:
            chosenUnit = int(input("Choose a Unit (1-5) > "))
            match chosenUnit:
                case 1| 1|1 | 1 :
                    price, serviceType = typeService_Charges(type_ofService, chosenUnit)
                    model = 'Toyota Vios MT'
                    print ("\nModel:",model)
                    print ("Color: Red")
                    print ("Seat Count: 5")
                    print ("Type of Service:",serviceType)
                    print ("Price: ₱",format(price,',.2f'))
                    break
                case 2| 2|2 | 2 :
                    price, serviceType = typeService_Charges(type_ofService, chosenUnit)
                    model = 'Toyota Altis AT'
                    print("\nModel:",model)
                    print ("Color: Gray")
                    print ("Seat Count: 5")
                    print ("Type of Service:",serviceType)
                    print ("Price: ₱",format(price,',.2f'))
                    break
                case 3| 3|3 | 3 :
                    price, serviceType = typeService_Charges(type_ofService, chosenUnit)
                    model = 'Toyota Camry'
                    print("\nModel:",model)
                    print ("Color: Black")
                    print ("Seat Count: 5")
                    print ("Type of Service:",serviceType)
                    print ("Price: ₱",format(price,',.2f'))
                    break
                case 4| 4|4 | 4 :
                    price, serviceType = typeService_Charges(type_ofService, chosenUnit)
                    model = 'Toyota Innova'
                    print("\nModel:",model )
                    print ("Color: Dark Red")
                    print ("Seat Count: 7")
                    print ("Type of Service:",serviceType)
                    print ("Price: ₱",format(price,',.2f'))
                    break
                case 5| 5|5 | 5 :
                    price, serviceType = typeService_Charges(type_ofService, chosenUnit)
                    model = 'Toyota Grandia'
                    print("\nModel:",model)
                    print ("Color: Light Black")
                    print ("Seat Count: 12")
                    print ("Type of Service:",serviceType)
                    print ("Price: ₱",format(price,',.2f'))
                    break
                case _:
                    raise ValueError
        except ValueError:
            print("Invalid input. Please type within the list: [1|2|3|4|5].\n")
            continue
    return price, model, serviceType

### This part of the code will determine if the user want a self-driven vehicle or a chaffuer type of service. Picking one or the other
### will determine the rates.
def typeService_Charges(type_ofService, chosenUnit):
    if type_ofService == 'S':
        serviceType = 'Self-Driven'
        if chosenUnit == 1:
            charge = 3285
        if chosenUnit == 2:
            charge = 4040
        if chosenUnit == 3:
            charge = 4830
        if chosenUnit == 4:
            charge = 4430
        if chosenUnit == 5:
            charge = 5550

    elif type_ofService == 'C':
        serviceType = 'Chauffeur'
        if chosenUnit == 1:
            charge = 3875
        if chosenUnit == 2:
            charge = 4650
        if chosenUnit == 3:
            charge = 5465
        if chosenUnit == 4:
            charge = 4705
        if chosenUnit == 5:
            charge = 6200

    return charge, serviceType


### This part will ask the user when will they pick up their rented vehicle.
def input_dateOfPickUp():
    while True:
        try:
            dateInput = input("When do you want pick your rental vechicle? ('MM/DD/YYYY') - ")
            datePickUp = datetime.strptime(dateInput,'%m/%d/%Y')
            if datePickUp <= datetime.today():
                raise ValueError
            else:
                break
        except ValueError:
            print("Inputted date is not applicable!\n")
            continue
    return dateInput

### This block of code will start the final stage of our program, the Calculation Stage. As the name it implies, it multiplies the number of
### days the unit got rented and its initialized rate.
def price_per_day():
    while True:
        try:
            days_rental = int(input("How many days will you rent this vehicle? "))
            if days_rental <= 0:
                raise ValueError
            break
        except ValueError:
            print("Invalid input. Please type a valid number of days.\n")
    data = []
    print('\n○-----------------------------○')
    print()
    for days in range(1, days_rental + 1):
        total_price = days * price
        data.append([days, format(total_price,',.2f')])
    print(tabulate(data, headers = ["Day", "Price(₱)"]))
    print('\n○-----------------------------○')
    return days_rental, total_price

### This will ask the user if they have a Discount Code where it could lessen the total price.
def discount(days_rental, total_price):
    print("#Special Offer! Type in your Discount Code to cheapen the price for all your travels. The rate of your chosen vehicle will be halved in price for every two days you got it rented.\n")
    validation = True
    totPrice = total_price
    while validation == True:
        ask_discount_code = input("Do you have a discount code? (Y/N): ").capitalize()
        if ask_discount_code in validation_options_Disagree:
            print("Please visit our official website for a chance to get a discount code!")
            validation = False
            break
        elif ask_discount_code in validation_options_Agree:
            discount_code = input("Discount Code: ")
            print()
            if discount_code == "IloveLogProg":
                totPrice = 0
                data = []
                print('\n○-----------------------------○')
                print()
                for days in range(1, days_rental + 1):
                    discounted_price = (days // 2) * (price / 2)
                    regular_price = (days - (days // 2)) * price
                    totPrice = discounted_price + regular_price
                    data.append([days, format(totPrice,',.2f')])
                print(tabulate(data, headers = ["Day", "Discount Price(₱)"]))
                print('\n○-----------------------------○')
                validation = False
                break
            else:
                print("Invalid discount code! Please confirm you have one and try again next time.\n")
        else:

            print("Invalid input! Please type either 'y' or 'n'.\n")
            continue
    return totPrice


### This will ask the user for their payment. Also, if they are not satisfied with their choice, they would have the option to choose something else.
def input_payment(discounted_total_price, validation_options_Disagree, validation_options_Agree, showcase_phase):
    payment_validation = True
    balance = 0
    while payment_validation:
        try:
            print("\nTotal Price: ₱",format(discounted_total_price,',.2f'))
            payment = int(input("Payment: ₱"))
            if payment < discounted_total_price:
                print("Payment not accepted. Reason: Insufficient\nEither attempt to input a new amount instead or find a more affordable car.")

                payment_or_retry = True
                while payment_or_retry:
                    payment_or_retry_vld = input('\nDo you want to input a new amount? (y/n) - ')
                    if payment_or_retry_vld in validation_options_Disagree:
                        payment_validation = False
                        print('\n\n\n<<------------------------------------------------------------------->>\n\n')
                        showcase_cars()
                        break
                    elif payment_or_retry_vld in validation_options_Agree:
                        break
                    else:
                        print("Invalid input. Please enter 'y' or 'n'.")
                        continue

            elif payment >= discounted_total_price:
                balance = payment - discounted_total_price
                print("\nThank you for your using our business. Please wait for a moment as we finalize your receipt...")
                showcase_phase = False
                break

        except ValueError:
            print("Invalid input. Please enter a valid payment.")
            continue
    return payment, balance, showcase_phase






'''Main Program'''



print("\nWelcome to our premier car rental site, this is your ultimate destination for hassle-free car rentals! Experience seamless booking, a wide selection of vehicles, and unmatched convenience.\n\nYour journey starts here...\n")


# Credential Stage

name, address, e_address, province = input_credentials()

## This While Loop will not end until the user press 'n'. It will make sure the user will always have a chance to change any specific
## details until they are satisfied.
while True:
    change_creds_vld = input('Is there something you want to change? (y/n) - ')
    if change_creds_vld in validation_options_Agree:
        name, address, e_address, province = change_credentials(name, address, e_address, province)
    elif change_creds_vld in validation_options_Disagree:
        break
    else:
        print("Invalid input. Please enter 'y' or 'n'.\n")

## This While Loop will not end until the user press 'y' or 'n'. If 'y', the program will continue normallly, but if 'n', it will call the
## pickUp_Province() function and will present a sub-menu.
while True:
    pickUp_Loc_vld = input('\nDo you want to the pick-up location to be the same as your address? (y/n) - ')
    if pickUp_Loc_vld in validation_options_Agree:
        pickUp_Loc = "'Same as your Address'"
        break
    elif pickUp_Loc_vld in validation_options_Disagree:
        print ("\nPossible Pick-Up Locations in",province,end=':\n')
        pickUp_Loc = pickUp_Province(province)
        break
    else:
        print("Invalid input. Please enter 'y' or 'n'.")

print('\n\n<<------------------------------------------------------------------->>\n\n')

# Showcase Stage

showcase_cars()

## This While Loop covers both the Showcase Stage and the Calculation Stage. If the user is not satisfied with their initial choice after doing all the
## calculations, they could go back to this very moment instantly.
showcase_phase = True
while showcase_phase:

    ## Type_of_Service Loop - (Start)
    type_ofService = input("\nPreffered Type of Service: (S - 'Self-Driven'/C - 'Chauffeur') - ")
    if type_ofService.upper() in ['S', 'C']:
        price, model, serviceType = choose_car(type_ofService.upper())


        change_showcase_vld = input('\nIs this the unit you want? (y/n) - ')
        if change_showcase_vld in validation_options_Disagree: ## - Repeat to the very first step of Type_of_Service Loop
            continue
        elif change_showcase_vld in validation_options_Agree: ## - End Type_of_Service_Validation Loop, Then continue to Calculation Stage
            pass
        else: ## Repeat to the very first step of Type_of_Service
            print("Invalid input. Restarting process... Next time, please enter 'y' or 'n'.\n")
            continue

    else: ## Repeat Type_of_Service Loop
        print("Invalid input. Please type within the list: [S|C].")
        continue


    print('\n\n<<------------------------------------------------------------------->>\n\n')

    # Next Step after the Showcase Stage: Calculation Stage

    datePickUp = input_dateOfPickUp()
    days_rental, total_price = price_per_day()
    print()
    discounted_total_price = discount(days_rental, total_price)
    payment, balance, showcase_phase = input_payment(discounted_total_price, validation_options_Disagree, validation_options_Agree, showcase_phase)


print('\n\n<<------------------------------------------------------------------->>\n\n')

# Receipt

print('   Reciept:')
print("\tFull Name:",name)
print("\tAddress:",address)
print("\tEmail Address:",e_address)
print("\tProvince:",province.upper())
print("\tPick-Up Location:",pickUp_Loc)
print("\tUnit Model:",model)
print("\tType of Service:",serviceType)
print("\tDays to Rent:",days_rental)
print("\tTotal Price: ₱",format(discounted_total_price,',.2f'))
print("\tUser's Payment: ₱",format(payment,',.2f'))
print("\tBalance: ₱",format(balance,',.2f'))
